apiVersion: v1
kind: Namespace
metadata:
  # Change namespace if you want
  name: slack
---
apiVersion: v1
kind: ConfigMap
metadata:
  # Change namespace if you want
  namespace: slack
  name: slack-config
data:
  SLACK_CLIENT_ID: ""
  SLACK_CLIENT_SECRET: ""
  SLACK_SIGNING_SECRET: ""
  SLACK_APP_TOKEN: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  # Change namespace if you want
  namespace: slack
  name: slack-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: slack-app
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: slack-app
    spec:
      containers:
      # Change container image if you want
      - image: sce06147/slack-app:latest
        imagePullPolicy: Always
        name: slack-app
        ports:
        - containerPort: 9000
        envFrom:
        - configMapRef:
            name: slack-config
---
apiVersion: v1
kind: Service
metadata:
  # Change namespace if you want
  namespace: slack
  name: slack-service
spec:
  ports:
    - port: 80
      targetPort: 9000
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: slack-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: slack
  name: slack-ingress
  annotations:
    # kubectl get clusterIssuer
    cert-manager.io/cluster-issuer: "letsencrypt-clusterissuer"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  # kubectl get ingressClass
  ingressClassName: "nginx"
  tls:
  - hosts:
    - hyunsu.scg.skku.ac.kr
    secretName: slack-tls
  rules:
  - host: hyunsu.scg.skku.ac.kr
    http:
      paths:
      - backend:
          service:
            name: slack-service
            port:
              number: 80
        path: /
        pathType: Prefix